# Generated by Django 3.0.3 on 2020-03-13 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('manager_position', models.BooleanField()),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=12)),
                ('email_address', models.EmailField(max_length=50)),
                ('emp_code', models.CharField(choices=[('IC ', 'Contractor'), ('FTE', 'Full Time')], default='FTE', max_length=3)),
                ('manager_name', models.ForeignKey(limit_choices_to={'position__manager_position': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_management.Employee')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee_management.Position')),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('start', models.CharField(max_length=255)),
                ('end', models.CharField(max_length=255)),
                ('allDay', models.BooleanField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_management.Employee')),
            ],
        ),
        migrations.RunSQL("INSERT INTO employee_management_position ('id', 'title', 'manager_position', 'color')  "
                          "VALUES (1,'JR Developer',0,'#f041d5'), (2,'Lead Developer',1,'#ff5900'), "
                          "(3,'HR Generalist',0,'#1e00ff'),(4,'HR Manager',1,'#141414');")
    ]
