# Generated by Django 3.0.3 on 2020-02-25 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('manager_position', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=12)),
                ('email_address', models.EmailField(max_length=50)),
                ('emp_code', models.CharField(max_length=3)),
                ('manager_name', models.ForeignKey(limit_choices_to={'position__manager_position': 1}, null=True,
                                                   on_delete=django.db.models.deletion.SET_NULL,
                                                   to='employee_management.Employee')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                               to='employee_management.Position')),
            ],
        ),
        migrations.RunSQL("INSERT INTO employee_management_position ('id', 'title', 'manager_position')  VALUES (1,"
                          "'JR Developer',0), (2,'Lead Developer',1), (3,'HR Generalist',0),(4,'HR Manager',1);")
    ]
